import Login from './components/Login'
import Signup from './components/Signup'
import { logout } from './components/UserFunctions'
import ShowSets from './components/ShowSets'
import Animals from './components/Animals'
import NotFound from './components/NotFound'
import Home from './components/Home'
import UploadDoc from './components/UploadDoc'
import firebase, { fbAuth } from './firebase'
